FROM registry.access.redhat.com/ubi8/python-311

# Set the working directory
WORKDIR /app

# Copy dependency info
COPY requirements.txt /app/

# Install dependencies
RUN pip3 install --no-cache-dir -r requirements.txt

# Add ENV variables
ENV DB_USER='python_backend'
ENV DB_PASS='O4&T(Z(mE5YX,%$I'
ENV DB_NAME='project'
ENV INSTANCE_CONNECTION_NAME='fall-fun-cs411:us-central1:sql-backend'

# Copy source code
COPY . /app

# Expose the port Cloud Run will use
EXPOSE 8080

# Start the FastAPI server using the dynamic port
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "$PORT"]