FROM registry.access.redhat.com/ubi8/python-311
WORKDIR .

# Copy dependency info
COPY requirements.txt ./

# Install dependencies
RUN pip3 install -r requirements.txt

# Add ENV variables
ENV DB_USER='python_backend'
ENV DB_PASS='O4&T(Z(mE5YX,%$I'
ENV DB_NAME='project'
ENV INSTANCE_CONNECTION_NAME='fall-fun-cs411:us-central1:sql-backend'

# Copy Source Code
COPY . .

# Expose PORT
EXPOSE 8000

# Run Server
CMD fastapi run api.py
